name: Update copyright year(s) in license file
on:
  schedule:
    - cron: "5 0 1 1 *" # 20xx-01-01 00:05
  workflow_dispatch: # Allow manual execution as well, in case the update fails.
env:
  branch-name-prefix: license/
jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find all LICENSE files
        id: find-all-license-files
        shell: bash
        # see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        # see https://gotohayato.com/content/558/
        run: |
          delimiter="ghadelimiter_$(openssl rand -hex 32)"
          readonly delimiter
          {
            echo "files<<${delimiter}"
            git ls-files ':(glob)**/LICENSE'
            echo "${delimiter}"
          } >> "${GITHUB_OUTPUT}"

      - name: Fetch already existing branches
        # FantasticFiasco/action-update-license-year@v3 tries to checkout the remote branch it has detected.
        # However, since it has not yet been fetched, the "git checkout" command fails.
        # see https://github.com/FantasticFiasco/action-update-license-year/blob/v3.0.0/src/main.js#L65
        shell: bash
        run: |
          # Note: "awk" can change the line separator using the "ORS" variable.
          #       However, when I actually tried it, it seems that the null character cannot be used.
          #       Therefore, the "tr" command is used to replace the newline with the null character.
          # Note: We pass the "-r" option to the "xargs" command so that the "git fetch" command will not be executed if the remote branch does not exist.
          #       see https://stackoverflow.com/a/8296746
          git ls-remote --heads origin '${{ env.branch-name-prefix }}*' \
            | awk '{ sub("^refs/heads/", "", $2); print $2 }' \
            | tr '\n' '\0' \
            | xargs -0r git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin

      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          # Use a personal access token instead of GITHUB_TOKEN to perform GitHub Actions on pull requests.
          # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          token: ${{ secrets.TRIGGER_WORKFLOW_GITHUB_TOKEN }}
          path: ${{ steps.find-all-license-files.outputs.files }}
          branchName: ${{ format('{0}copyright-to-{1}', env.branch-name-prefix, '{{currentYear}}') }}
          commitTitle: |
            docs(license): update copyright year(s)
          prTitle: |
            docs(license): update copyright year(s)
          prBody: |
            This PR has been generated by [FantasticFiasco/action-update-license-year v3](https://github.com/FantasticFiasco/action-update-license-year/tree/v3).
